---
version: '3.4'
services:

  ibft2_single_besu_node:
    image: ghcr.io/lacchain/lacchain-besu:23.7.3.0-amd64
      #environment:
      #- BESU_PUBLIC_KEY_DIRECTORY=${BESU_PUBLIC_KEY_DIRECTORY}
    command: &base_options [
      "--config-file=/config/config.toml",
      "--genesis-file=/config/genesis.json",
      "--node-private-key-file=/opt/besu/keys/key",
      "--rpc-http-api=WEB3,ETH,NET",
      "--rpc-ws-api=WEB3,ETH,NET,EEA,ADMIN"]
    volumes:
      #- public-keys:${BESU_PUBLIC_KEY_DIRECTORY}
      - ./config/config.toml:/config/config.toml
      - ./config/genesis.json:/config/genesis.json
      - ./config/keys:/opt/besu/keys
    ports:
      - 8545:8545/tcp
      - 8546:8546/tcp
      
volumes:
  public-keys:
